version: '3.8'

services:
  broker:
    image: redis:7
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - redisdata:/data

  db:
    image: mariadb:10.11
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb", "-upaperess", "-ppaperless", "-e", "SELECT 1;"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - mariadbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: paperless
      MYSQL_USER: paperless
      MYSQL_PASSWORD: paperless
      MYSQL_ROOT_PASSWORD: paperless

  webserver:
    image: paperlessastra/paperless-astra:latest
    restart: unless-stopped
    depends_on:
      - broker
      - db
      - tika
      - gotenberg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./consume:/usr/src/paperless/consume
      - ./export:/usr/src/paperless/export
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBPORT: 3306
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_URL: http://localhost:8000
      PAPERLESS_SECRET_KEY: change-me
      PAPERLESS_TIME_ZONE: UTC
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
    ports:
      - "8000:8000"

  tika:
    image: apache/tika:3.1.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "9998:9998"

  gotenberg:
    image: gotenberg/gotenberg:7.10
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3000:3000"

volumes:
  data:
  media:
  mariadbdata:
  redisdata: